### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cekees** [compeco/rendering-functions#1]
## TODO
- [x] example mesh data structures for triangular mesh
- [x] basic continuous Galerkin contour (filled contours, etc) example
- [ ] basic quiver and stream plot example for CG velocity field
- [ ] patch based plotting example

**Comment by vpasour** [comment]
These are crazy!
